### ISSUE TITLE
Manual URL navigation

### ISSUE THREAD

**Issue by zalky** [venantius/accountant#53] opened 2018-01-20 19:42 UTC
Hi, I seem to be having difficulty setting up accountant in a way that resolves client routable URLs without sending a remote request.

I'm using bidi routes:

```clj
["/" {""      :home
      "doc"   :doc
      "login" :login
      true    :not-found}]
```

I run this at init:

```clj
(accountant.core/configure-navigation!
 {:nav-handler #(update-page-in-db (bidi/match-route app-routes %))
  :path-exists? #(boolean (bidi/match-route app-routes %))})
(accountant.core/dispatch-current!)
```

And I can successfully navigate to pages using:

```clj
(accountant.core/navigate! "/doc")
(accountant.core/navigate! "/")
```

However when I manually type in the url to point to `".../doc"`, it makes a full request to the remote, which I'd like to avoid. My understanding was that if the route is navigable (via `:path-exists?`), then accountant should prevent that from happening and just route client side. Unfortunately I just cannot seem to figure out how to do this when manually typing in the URL.

Am I misunderstanding something?

**Comment by venantius** [comment] 2018-01-20 20:25
Okay, so I'll confess to not being a complete expert at how browsers work. However, my guess is that manually typing in the url to the browser circumvents the mechanism by which Accountant operates entirely. Accountant relies on the HTML5 history API, and when you type in an address to your browser's URL you're essentially telling the browser to ignore any content currently on the page (including whatever JS may be running) and to perform a full request. So in that context I'm afraid what you're describing is expected behavior.

**Comment by venantius** [comment] 2018-01-20 20:35
(that means that by virtue of how browsers work there probably isn't another solution that will accomplish what you want. But I could be wrong - like I said, I'm not an expert :))

**Comment by iku000888** [comment] 2018-01-21 00:22
@zalky 

I agree with David; the user gets to type whatever url and press enter and there is nothing to do about it.

Perhaps a more productive question is: what is the problem when a user can access whatever url?

**Comment by zalky** [comment] 2018-01-21 17:02
@venantius , ah, I see. I was worried I was doing something wrong. Appreciate the clarification, and thanks for putting together this library!

**Comment by venantius** [comment] 2018-01-21 17:30
No, nothing wrong with what you're doing. I'm going to close this issue, since there doesn't seem to be a need for follow-up here.

**Closed by venantius** 2018-01-21 17:30 UTC

**Comment by zalky** [comment] 2018-01-21 17:48
@iku000888 , well, it's not just whatever URL, but specifically those URLs that resolve in the client-side routing table. Presumably in a SPA you do not need a remote request with a full page navigation to get to those routes. It is certainly not the end of the world. I was asking because, not having the deepest understanding of how browsers work, I had assumed that navigating via

**Comment by zalky** [comment] 2018-01-25 23:37
@venantius , I don't suppose you have a recommended solution for how to deal with those client-side navigations on the server? I have some simple middleware that intercepts client routes and responds with my client app.

This seems to work for all top level navigations, such as `"/doc"`. However, as soon as I try to add route-params to my uri, such as `"/doc/123"`, the routing fails. The browser requests `"doc/123"`, and receives the client, which is great, but then proceeds to look for resources at `"/doc/js/..."` and `"/doc/css/..."`, which don't exist. I suspect that I need to be doing some kind of redirection, I'm just not sure what exactly.

**Comment by venantius** [comment] 2018-01-25 23:46
@zalky in your `index.html` you should link to your js and css files starting with a forward slash. That way the server will load from the server root (e.g. `/js/...`). Otherwise it'll try to load assets from the relative URL your client is at.

**Comment by zalky** [comment] 2018-01-26 00:17
@venantius , thanks that did seem to be the problem, the only difficulty now is that while I can change my own html, all the script tags generated by the clojurescript compiler are relative. So `http://localhost:4000/doc/js/main.out/cljs_deps.js` is failing to resolves because google closure inserts `document.write('<script src="js/main.out/goog/base.js"></script>');` relative paths into `main.js`.

**Comment by zalky** [comment] 2018-01-26 02:01
Ok, well I wasn't able to figure out if it was possible to get forward slashes out of the clojurescript compiler, but I was able to deal with it by modifying my middleware slightly. In case it helps anyone:

```clj
(defn wrap-client-routes
  [client]
  (let [handler (GET "*" _ client)]
    (fn [{:keys [uri] :as request}]
      (if (bidi.bidi/match-route client-routes uri)
        (handler request)
        (when-let [uri* (re-find #"/js/main.out.*" uri)]
          (ring.util.response/resource-response uri*))))))
```
This handles

**Comment by zalky** [comment] 2018-01-26 06:27
Scratch that. You can add forward slashes in the compiler `:assets-path`.
